
##########################
# Create Development image
##########################
FROM node:16 as development

WORKDIR /app

# Install dependency packages
COPY package.json .
COPY services/common-api/package.json services/common-api/
COPY services/common-interfaces/package.json services/common-interfaces/
COPY services/common-utils/package.json services/common-utils/
COPY services/auth/package.json services/auth/
RUN yarn install

# Copy source codes
COPY services/tsconfig.base.json services/
COPY services/common-api services/common-api
COPY services/common-interfaces services/common-interfaces
COPY services/common-utils services/common-utils
COPY services/auth services/auth

# Build project
RUN yarn workspaces run build

# Stat app in development mode
CMD yarn workspace @deckery/auth dev