apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: deckery-auth
build:
  artifacts:
    - image: localhost:30500/deckery/auth
      context: ..
      docker:
        dockerfile: services/auth/Dockerfile
      sync:
        infer:
        - "services/auth/**"
        
deploy:
  helm:
    releases: 
    - name: deckery-auth
      chartPath: ../_helm/charts/auth
      artifactOverrides:
        auth: localhost:30500/deckery/auth
      imageStrategy:
        helm: {}