apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: deckery-auth

build:
  artifacts:
    - image: auth-development
      context: ..
      docker:
        dockerfile: services/auth/Dockerfile.dev
      sync:
        infer: 
        - services/tsconfig.base.json
        - services/auth/**/*
        - services/common-api/**/*
        - services/common-utils/**/*
        - services/common-interfaces/**/*
    - image: auth
      context: ..
      docker:
        dockerfile: services/auth/Dockerfile
      requires: 
      - image: auth-development
        alias: DEVIMG

deploy:
  helm:
    releases: 
    - name: deckery-auth
      chartPath: ../_helm/charts/auth
      artifactOverrides:
        auth: auth
      imageStrategy:
        helm: {}
profiles: 
- name: dev
  activation:
  - command: dev
  patches:
    - op: remove
      path: /build/artifacts/1
    - op: replace
      path: /deploy/helm/releases/0/artifactOverrides/auth
      value: auth-development