apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: deckery-auth

build:
  artifacts:
    - image: localhost:30500/deckery/auth
      context: ..
      docker:
        dockerfile: services/auth/Dockerfile
      sync:
        infer:
        - "services/auth/src/**"
        - "services/common/src/**"
deploy:
  helm:
    releases: 
    - name: deckery-auth
      chartPath: ../_helm/charts/auth
      artifactOverrides:
        auth: localhost:30500/deckery/auth
      imageStrategy:
        helm: {}
profiles: 
- name: dev
  activation:
  - command: dev
  patches:
    - op: add
      path: /build/artifacts/0/docker/target
      value: builder