apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: deckery-game-ui
build:
  artifacts:
    - image: localhost:30500/deckery/game-ui
      context: ..
      docker:
        dockerfile: services/game-ui/Dockerfile
      sync:
        manual:
        - src: services/game-ui/src/**/*
          dest: .
        - src: services/common/src/**/*
          dest: .
deploy:
  helm:
    releases: 
    - name: deckery-game-ui
      chartPath: ../_helm/charts/game-ui
      artifactOverrides:
        game_ui: localhost:30500/deckery/game-ui
      imageStrategy:
        helm: {}
profiles: 
- name: dev
  activation:
  - command: dev
  patches:
    - op: add
      path: /build/artifacts/0/docker/target
      value: development