apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: deckery-game-ui
build:
  artifacts:
    - image: localhost:30500/deckery/game-ui
      context: ../services
      docker:
        dockerfile: game-ui/Dockerfile
      sync:
        infer:
          - "game-ui/src/**"
          - "game-ui/public/**"
          - "common/**"
deploy:
  helm:
    releases: 
    - name: deckery-game-ui
      chartPath: ../_helm/charts/game-ui
      artifactOverrides:
        game_ui: localhost:30500/deckery/game-ui
      imageStrategy:
        helm: {}