apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: deckery-infra
deploy:
  helm:
    releases: 
    - name: deckery-infra
      chartPath: ../_helm/charts/infra
      imageStrategy:
        helm: {}
