apiVersion: apps/v1
kind: Deployment
metadata:
  name: deckery-game-ui
spec:
  selector:
    matchLabels:
      app: deckery-game-ui
  template:
    metadata:
      labels:
        app: deckery-game-ui
    spec:      
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.game_ui.repository }}:{{.Values.game_ui.tag}}
          imagePullPolicy: {{ .Values.game_ui.pullPolicy }}
          ports:
          - containerPort: 3000
        
