apiVersion: v1
kind: Service
metadata:
  name: deckery-web-ui
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.web_ui.service.type }}
  selector:
    app: deckery-web-ui
  ports:
  - port: {{ .Values.web_ui.service.externalPort }}
    targetPort: {{ .Values.web_ui.service.internalPort }}
    protocol: TCP
    name: {{ .Chart.Name }}