web_ui:
  repository: localhost:30500/deckery/web-ui
  tag: latest
  pullPolicy: IfNotPresent
  enabled: true

game_ui:
  repository: localhost:30500/deckery/game-ui
  tag: latest
  pullPolicy: IfNotPresent
  enabled: true

auth:
  repository: localhost:30500/deckery/auth
  tag: latest
  pullPolicy: IfNotPresent
  
  service:
    internalPort: 3000
    externalPort: 80